package com.anenji.monitor;
import android.app.*;import android.content.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.text.SimpleDateFormat;import java.util.*;
public class MonitorService extends Service{
 static final String BASE="https://api.dessmonitor.com/public/",KEY="bnrl_frRFjEz8Mkn",MON="monitor",AL="alerts";String token,secret,user,pass,pn,sn;int devcode,devaddr;boolean known,lastGrid;volatile boolean stop;
 public void onCreate(){super.onCreate();NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel(MON,"Anenji Monitor",NotificationManager.IMPORTANCE_LOW));n.createNotificationChannel(new NotificationChannel(AL,"Мережа 220 В",NotificationManager.IMPORTANCE_HIGH));startForeground(1,note(MON,"Anenji Monitor","Підключення до SmartESS…",true));}
 public int onStartCommand(Intent i,int f,int id){android.content.SharedPreferences p=getSharedPreferences("cfg",MODE_PRIVATE);user=p.getString("u","");pass=p.getString("p","");stop=false;new Thread(()->{while(!stop&&getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("running",false)){try{Poll x=poll();if(known&&x.grid!=lastGrid)alert(x.grid);lastGrid=x.grid;known=true;send("● SmartESS підключено","Мережа: "+(x.grid?String.format(Locale.US,"Є • %.0f В",x.volts):"НЕМАЄ"),x.battery==null?"АКБ: —":"АКБ: "+fmt(x.battery)+"%",x.load==null?"Навантаження: —":"Навантаження: "+fmt(x.load)+" Вт","Останнє оновлення: "+new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date()),"");}catch(Exception e){token=null;secret=null;send("● Помилка підключення","Мережа: —","АКБ: —","Навантаження: —","Остання спроба: "+new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date()),friendly(e));}try{Thread.sleep(60000);}catch(Exception e){break;}}}).start();return START_STICKY;}
 Poll poll()throws Exception{auth();JSONObject pl=req("queryPlants",m("pagesize","50"));JSONArray plants=pl.getJSONObject("dat").getJSONArray("plant");if(plants.length()==0)throw new Exception("NO_PLANT");String pid=String.valueOf(plants.getJSONObject(0).get("pid"));
 JSONObject co=req("webQueryCollectorsEs",m("pid",pid,"page","0","pagesize","50"));JSONArray ca=co.getJSONObject("dat").optJSONArray("collector");if(ca==null||ca.length()==0)throw new Exception("NO_COLLECTOR");pn=ca.getJSONObject(0).optString("pn");if(pn.isEmpty())throw new Exception("NO_PN");
 JSONObject cd=req("queryCollectorDevices",m("pn",pn));JSONArray da=cd.getJSONObject("dat").optJSONArray("dev");if(da==null||da.length()==0)throw new Exception("NO_DEVICE");JSONObject d=da.getJSONObject(0);sn=d.optString("sn");devcode=d.optInt("devcode");devaddr=d.optInt("devaddr");
 JSONArray a=req("queryDeviceLastData",m("pn",pn,"devcode",String.valueOf(devcode),"devaddr",String.valueOf(devaddr),"sn",sn,"i18n","en")).getJSONArray("dat");Double volts=null,bat=null,load=null;
 for(int z=0;z<a.length();z++){JSONObject o=a.getJSONObject(z);String t=o.optString("title").toLowerCase(Locale.ROOT);Double v=num(o.opt("val"));if(v==null)continue;if(volts==null&&(t.contains("grid voltage")||t.contains("mains voltage")||t.contains("utility voltage")||t.contains("ac input voltage")))volts=v;if(bat==null&&(t.contains("battery capacity")||t.contains("battery soc")||t.equals("battery")))bat=v;if(load==null&&(t.contains("load power")||t.contains("output active power")||t.equals("load")))load=v;}
 if(volts==null)throw new Exception("NO_GRID");Poll x=new Poll();x.volts=volts;x.grid=volts>100;x.battery=bat;x.load=load;return x;}
 void auth()throws Exception{if(token!=null)return;String salt=String.valueOf(System.currentTimeMillis());String tail="&action=authSource&usr="+enc(user)+"&company-key="+KEY+"&source=1&_app_client_=web&_app_id_=ha-dessmonitor&_app_version_=2.4.0";JSONObject j=get(BASE+"?sign="+sha(salt+sha(pass)+tail)+"&salt="+salt+tail);if(j.optInt("err",-1)!=0)throw new Exception("LOGIN");JSONObject d=j.optJSONObject("dat");if(d==null)throw new Exception("LOGIN");token=d.getString("token");secret=d.getString("secret");}
 JSONObject req(String ac,LinkedHashMap<String,String> p)throws Exception{String salt=String.valueOf(System.currentTimeMillis());StringBuilder t=new StringBuilder("&action=").append(ac);for(Map.Entry<String,String>e:p.entrySet())t.append("&").append(e.getKey()).append("=").append(enc(e.getValue()));JSONObject j=get(BASE+"?sign="+sha(salt+secret+token+t)+"&salt="+salt+"&token="+token+t);if(j.optInt("err",-1)!=0)throw new Exception("API");return j;}
 JSONObject get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(20000);int code=c.getResponseCode();if(code<200||code>=300)throw new Exception("HTTP");try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return new JSONObject(s.toString());}}
 void send(String s,String g,String b,String l,String tm,String e){Intent i=new Intent("com.anenji.monitor.STATUS");i.setPackage(getPackageName());i.putExtra("state",s);i.putExtra("grid",g);i.putExtra("batt",b);i.putExtra("load",l);i.putExtra("last",tm);i.putExtra("error",e);sendBroadcast(i);getSystemService(NotificationManager.class).notify(1,note(MON,"Anenji Monitor",g+" • "+tm.replace("Останнє оновлення: ",""),true));}
 void alert(boolean on){getSystemService(NotificationManager.class).notify(on?3:2,note(AL,on?"Світло з’явилося":"Зникла мережа 220 В",on?"SmartESS знову бачить зовнішню мережу":"Інвертор не бачить зовнішню мережу",false));}
 Notification note(String ch,String t,String s,boolean ongoing){return new Notification.Builder(this,ch).setSmallIcon(android.R.drawable.ic_lock_idle_charging).setContentTitle(t).setContentText(s).setOngoing(ongoing).setAutoCancel(!ongoing).build();}
 static String friendly(Exception e){String x=e.getMessage();if("LOGIN".equals(x))return "Не вдалося увійти в SmartESS. Перевір логін і пароль.";if("NO_GRID".equals(x))return "SmartESS підключено, але показник напруги мережі не знайдено.";if("NO_DEVICE".equals(x)||"NO_COLLECTOR".equals(x)||"NO_PN".equals(x)||"NO_PLANT".equals(x))return "Не вдалося знайти інвертор у SmartESS.";return "Немає відповіді SmartESS або інтернету.";}
 static Double num(Object o){if(o==null)return null;try{return Double.parseDouble(String.valueOf(o).replace(",",".").replaceAll("[^0-9.\\-]",""));}catch(Exception e){return null;}}static String fmt(double d){return Math.abs(d-Math.rint(d))<.01?String.valueOf((long)Math.rint(d)):String.format(Locale.US,"%.1f",d);}
 static LinkedHashMap<String,String>m(String...x){LinkedHashMap<String,String>r=new LinkedHashMap<>();for(int i=0;i<x.length;i+=2)r.put(x[i],x[i+1]);return r;}static String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-1").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder r=new StringBuilder();for(byte x:b)r.append(String.format("%02x",x));return r.toString();}
 public void onDestroy(){stop=true;super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}static class Poll{boolean grid;double volts;Double battery,load;}
}